package com.gcu.taskmanager.model;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Represents an event in the task management system.
 * This entity maps to the "events" table in the database.
 * Each event belongs to one user and can be used for appointments,
 * birthdays, concerts, reservations, sporting events, and other planned events.
 */
@Entity
@Table(name = "events")
public class Event
{
    /**
     * Unique identifier for the event.
     * This value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Stores the title or name of the event.
     */
    @Column(name = "title", nullable = false)
    private String title;

    /**
     * Stores the event description.
     */
    @Column(name = "description")
    private String description;

    /**
     * Stores the event category.
     * Example values: APPOINTMENT, BIRTHDAY, CONCERT, RESERVATION, SPORT, OTHER.
     */
    @Column(name = "event_category")
    private String eventCategory;

    /**
     * Stores the date of the event.
     */
    @Column(name = "event_date", nullable = false)
    private LocalDate eventDate;

    /**
     * Stores the time of the event.
     */
    @Column(name = "event_time")
    private LocalTime eventTime;

    /**
     * Stores the event location if one is provided.
     */
    @Column(name = "location")
    private String location;

    /**
     * References the user who owns this event.
     * Many events can belong to one user.
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Default no-argument constructor required by JPA.
     */
    public Event()
    {
        super();
    }

    /**
     * Full constructor used to create an event with all required fields except ID.
     *
     * @param title The event title
     * @param description The event description
     * @param eventCategory The event category
     * @param eventDate The event date
     * @param eventTime The event time
     * @param location The event location
     * @param user The user who owns the event
     */
    public Event(String title, String description, String eventCategory, LocalDate eventDate,
                 LocalTime eventTime, String location, User user)
    {
        super();
        this.title = title;
        this.description = description;
        this.eventCategory = eventCategory;
        this.eventDate = eventDate;
        this.eventTime = eventTime;
        this.location = location;
        this.user = user;
    }

    /**
     * Gets the event ID.
     *
     * @return The event ID
     */
    public Long getId()
    {
        return id;
    }

    /**
     * Sets the event ID.
     *
     * @param id The event ID
     */
    public void setId(Long id)
    {
        this.id = id;
    }

    /**
     * Gets the event title.
     *
     * @return The event title
     */
    public String getTitle()
    {
        return title;
    }

    /**
     * Sets the event title.
     *
     * @param title The event title
     */
    public void setTitle(String title)
    {
        this.title = title;
    }

    /**
     * Gets the event description.
     *
     * @return The event description
     */
    public String getDescription()
    {
        return description;
    }

    /**
     * Sets the event description.
     *
     * @param description The event description
     */
    public void setDescription(String description)
    {
        this.description = description;
    }

    /**
     * Gets the event category.
     *
     * @return The event category
     */
    public String getEventCategory()
    {
        return eventCategory;
    }

    /**
     * Sets the event category.
     *
     * @param eventCategory The event category
     */
    public void setEventCategory(String eventCategory)
    {
        this.eventCategory = eventCategory;
    }

    /**
     * Gets the event date.
     *
     * @return The event date
     */
    public LocalDate getEventDate()
    {
        return eventDate;
    }

    /**
     * Sets the event date.
     *
     * @param eventDate The event date
     */
    public void setEventDate(LocalDate eventDate)
    {
        this.eventDate = eventDate;
    }

    /**
     * Gets the event time.
     *
     * @return The event time
     */
    public LocalTime getEventTime()
    {
        return eventTime;
    }

    /**
     * Sets the event time.
     *
     * @param eventTime The event time
     */
    public void setEventTime(LocalTime eventTime)
    {
        this.eventTime = eventTime;
    }

    /**
     * Gets the event location.
     *
     * @return The event location
     */
    public String getLocation()
    {
        return location;
    }

    /**
     * Sets the event location.
     *
     * @param location The event location
     */
    public void setLocation(String location)
    {
        this.location = location;
    }

    /**
     * Gets the user who owns this event.
     *
     * @return The user who owns the event
     */
    public User getUser()
    {
        return user;
    }

    /**
     * Sets the user who owns this event.
     *
     * @param user The user who owns the event
     */
    public void setUser(User user)
    {
        this.user = user;
    }

    /**
     * Gets the event name for frontend display.
     * This allows Thymeleaf to use event.name while the backend stores the value as title.
     *
     * @return The event title
     */
    public String getName()
    {
        return title;
    }

    /**
     * Sets the event name from frontend form input.
     * This maps the frontend name field to the backend title field.
     *
     * @param name The event name entered from the frontend
     */
    public void setName(String name)
    {
        this.title = name;
    }

    /**
     * Gets the combined event date and event time for frontend display.
     * This allows Thymeleaf to use event.dateTime.
     *
     * @return The event date and event time combined as LocalDateTime,
     *         or null if no event date exists
     */
    public LocalDateTime getDateTime()
    {
        if (eventDate == null)
        {
            return null;
        }

        if (eventTime == null)
        {
            return eventDate.atStartOfDay();
        }

        return eventDate.atTime(eventTime);
    }

    /**
     * Sets the event date and event time from frontend datetime input.
     * This maps the frontend dateTime field to the backend eventDate and eventTime fields.
     *
     * @param dateTime The combined date and time entered from the frontend
     */
    public void setDateTime(LocalDateTime dateTime)
    {
        if (dateTime != null)
        {
            this.eventDate = dateTime.toLocalDate();
            this.eventTime = dateTime.toLocalTime();
        }
    }
}