package com.gcu.taskmanager.model;

import java.time.LocalTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Represents a recurring task in the task management system.
 * This entity maps to the "recurring_tasks" table in the database.
 * Each recurring task belongs to one user.
 */
@Entity
@Table(name = "recurring_tasks")
public class RecurringTask
{
    /**
     * Unique identifier for the recurring task.
     * This value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Stores the title of the recurring task.
     */
    @Column(name = "title", nullable = false)
    private String title;

    /**
     * Stores the description of the recurring task.
     */
    @Column(name = "description")
    private String description;

    /**
     * Stores the recurrence type for the task.
     * Example values: DAILY, WEEKLY, MONTHLY.
     */
    @Column(name = "recurrence_type", nullable = false)
    private String recurrenceType;

    /**
     * Stores the day of the week for weekly recurring tasks.
     * Example values: Mon, Tue, Wed, Thu, Fri, Sat, Sun.
     */
    @Column(name = "day_of_week")
    private String dayOfWeek;

    /**
     * Stores the day of the month for monthly recurring tasks.
     * Example values: 1 through 31.
     */
    @Column(name = "day_of_month")
    private Integer dayOfMonth;

    /**
     * Stores the time associated with the recurring task.
     */
    @Column(name = "task_time")
    private LocalTime taskTime;

    /**
     * Stores the priority level of the recurring task.
     * Example values may range from 1 to 5.
     */
    @Column(name = "priority")
    private Integer priority;

    /**
     * Stores the location associated with the recurring task.
     */
    @Column(name = "location")
    private String location;

    /**
     * Indicates whether the recurring task has been completed.
     */
    @Column(name = "completed", nullable = false)
    private boolean completed;

    /**
     * References the user who owns this recurring task.
     * Many recurring tasks can belong to one user.
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Default no-argument constructor required by JPA.
     */
    public RecurringTask()
    {
        super();
        this.completed = false;
    }

    /**
     * Full constructor used to create a recurring task with all required fields except ID.
     *
     * @param title The title of the recurring task
     * @param description The description of the recurring task
     * @param recurrenceType The recurrence type of the recurring task
     * @param dayOfWeek The day of the week for weekly recurrence
     * @param dayOfMonth The day of the month for monthly recurrence
     * @param taskTime The time associated with the recurring task
     * @param priority The priority level of the recurring task
     * @param location The location associated with the recurring task
     * @param completed The completion status of the recurring task
     * @param user The user who owns the recurring task
     */
    public RecurringTask(String title, String description, String recurrenceType, String dayOfWeek,
                         Integer dayOfMonth, LocalTime taskTime, Integer priority,
                         String location, boolean completed, User user)
    {
        super();
        this.title = title;
        this.description = description;
        this.recurrenceType = recurrenceType;
        this.dayOfWeek = dayOfWeek;
        this.dayOfMonth = dayOfMonth;
        this.taskTime = taskTime;
        this.priority = priority;
        this.location = location;
        this.completed = completed;
        this.user = user;
    }

    /**
     * Gets the recurring task ID.
     *
     * @return The recurring task ID
     */
    public Long getId()
    {
        return id;
    }

    /**
     * Sets the recurring task ID.
     *
     * @param id The recurring task ID
     */
    public void setId(Long id)
    {
        this.id = id;
    }

    /**
     * Gets the title of the recurring task.
     *
     * @return The title
     */
    public String getTitle()
    {
        return title;
    }

    /**
     * Sets the title of the recurring task.
     *
     * @param title The title
     */
    public void setTitle(String title)
    {
        this.title = title;
    }

    /**
     * Gets the description of the recurring task.
     *
     * @return The description
     */
    public String getDescription()
    {
        return description;
    }

    /**
     * Sets the description of the recurring task.
     *
     * @param description The description
     */
    public void setDescription(String description)
    {
        this.description = description;
    }

    /**
     * Gets the recurrence type.
     *
     * @return The recurrence type
     */
    public String getRecurrenceType()
    {
        return recurrenceType;
    }

    /**
     * Sets the recurrence type.
     *
     * @param recurrenceType The recurrence type
     */
    public void setRecurrenceType(String recurrenceType)
    {
        this.recurrenceType = recurrenceType;
    }

    /**
     * Gets the day of the week.
     *
     * @return The day of the week
     */
    public String getDayOfWeek()
    {
        return dayOfWeek;
    }

    /**
     * Sets the day of the week.
     *
     * @param dayOfWeek The day of the week
     */
    public void setDayOfWeek(String dayOfWeek)
    {
        this.dayOfWeek = dayOfWeek;
    }

    /**
     * Gets the day of the month.
     *
     * @return The day of the month
     */
    public Integer getDayOfMonth()
    {
        return dayOfMonth;
    }

    /**
     * Sets the day of the month.
     *
     * @param dayOfMonth The day of the month
     */
    public void setDayOfMonth(Integer dayOfMonth)
    {
        this.dayOfMonth = dayOfMonth;
    }

    /**
     * Gets the task time.
     *
     * @return The task time
     */
    public LocalTime getTaskTime()
    {
        return taskTime;
    }

    /**
     * Sets the task time.
     *
     * @param taskTime The task time
     */
    public void setTaskTime(LocalTime taskTime)
    {
        this.taskTime = taskTime;
    }

    /**
     * Gets the priority level.
     *
     * @return The priority level
     */
    public Integer getPriority()
    {
        return priority;
    }

    /**
     * Sets the priority level.
     *
     * @param priority The priority level
     */
    public void setPriority(Integer priority)
    {
        this.priority = priority;
    }

    /**
     * Gets the location.
     *
     * @return The location
     */
    public String getLocation()
    {
        return location;
    }

    /**
     * Sets the location.
     *
     * @param location The location
     */
    public void setLocation(String location)
    {
        this.location = location;
    }

    /**
     * Checks whether the recurring task is completed.
     *
     * @return true if completed, false otherwise
     */
    public boolean isCompleted()
    {
        return completed;
    }

    /**
     * Sets the completion status of the recurring task.
     *
     * @param completed The completion status
     */
    public void setCompleted(boolean completed)
    {
        this.completed = completed;
    }

    /**
     * Gets the user who owns this recurring task.
     *
     * @return The user who owns the recurring task
     */
    public User getUser()
    {
        return user;
    }

    /**
     * Sets the user who owns this recurring task.
     *
     * @param user The user who owns the recurring task
     */
    public void setUser(User user)
    {
        this.user = user;
    }

    /**
     * Gets the recurring task name for frontend display.
     * This allows Thymeleaf to use task.name while the backend stores the value as title.
     *
     * @return The recurring task title
     */
    public String getName()
    {
        return title;
    }

    /**
     * Sets the recurring task name from frontend form input.
     * This maps the frontend name field to the backend title field.
     *
     * @param name The recurring task name entered from the frontend
     */
    public void setName(String name)
    {
        this.title = name;
    }

    /**
     * Gets the recurring task address for frontend display.
     * This allows Thymeleaf to use task.address while the backend stores the value as location.
     *
     * @return The recurring task location
     */
    public String getAddress()
    {
        return location;
    }

    /**
     * Sets the recurring task address from frontend form input.
     * This maps the frontend address field to the backend location field.
     *
     * @param address The recurring task address entered from the frontend
     */
    public void setAddress(String address)
    {
        this.location = address;
    }

    /**
     * Gets the recurring task notes for frontend display.
     * This allows Thymeleaf to use task.notes while the backend stores the value as description.
     *
     * @return The recurring task description
     */
    public String getNotes()
    {
        return description;
    }

    /**
     * Sets the recurring task notes from frontend form input.
     * This maps the frontend notes field to the backend description field.
     *
     * @param notes The recurring task notes entered from the frontend
     */
    public void setNotes(String notes)
    {
        this.description = notes;
    }

    /**
     * Gets the recurring task time for frontend form compatibility.
     *
     * @return The recurring task time
     */
    public LocalTime getTime()
    {
        return taskTime;
    }

    /**
     * Sets the recurring task time from frontend form input.
     *
     * @param time The time entered from the frontend
     */
    public void setTime(LocalTime time)
    {
        this.taskTime = time;
    }
}