package com.gcu.taskmanager.model;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Represents a standard task in the task management system.
 * This entity maps to the "tasks" table in the database.
 * Each task belongs to one user.
 */
@Entity
@Table(name = "tasks")
public class Task
{
    /**
     * Unique identifier for the task.
     * This value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Stores the title of the task.
     */
    @Column(name = "title", nullable = false)
    private String title;

    /**
     * Stores the description of the task.
     */
    @Column(name = "description")
    private String description;

    /**
     * Stores the due date of the task.
     */
    @Column(name = "due_date")
    private LocalDate dueDate;

    /**
     * Stores the due time of the task.
     */
    @Column(name = "due_time")
    private LocalTime dueTime;

    /**
     * Stores the priority level of the task.
     * Example values may range from 1 to 5.
     */
    @Column(name = "priority")
    private Integer priority;

    /**
     * Stores the task location if one is provided.
     */
    @Column(name = "location")
    private String location;

    /**
     * Indicates whether the task has been completed.
     */
    @Column(name = "completed", nullable = false)
    private boolean completed;

    /**
     * References the user who owns this task.
     * Many tasks can belong to one user.
     */
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /**
     * Default no-argument constructor required by JPA.
     */
    public Task()
    {
        super();
        this.completed = false;
    }

    /**
     * Full constructor used to create a task with all required fields except ID.
     *
     * @param title The title of the task
     * @param description The description of the task
     * @param dueDate The due date of the task
     * @param dueTime The due time of the task
     * @param priority The priority level of the task
     * @param location The location associated with the task
     * @param completed The completion status of the task
     * @param user The user who owns the task
     */
    public Task(String title, String description, LocalDate dueDate, LocalTime dueTime,
                Integer priority, String location, boolean completed, User user)
    {
        super();
        this.title = title;
        this.description = description;
        this.dueDate = dueDate;
        this.dueTime = dueTime;
        this.priority = priority;
        this.location = location;
        this.completed = completed;
        this.user = user;
    }

    /**
     * Gets the task ID.
     *
     * @return The task ID
     */
    public Long getId()
    {
        return id;
    }

    /**
     * Sets the task ID.
     *
     * @param id The task ID
     */
    public void setId(Long id)
    {
        this.id = id;
    }

    /**
     * Gets the task title.
     *
     * @return The task title
     */
    public String getTitle()
    {
        return title;
    }

    /**
     * Sets the task title.
     *
     * @param title The task title
     */
    public void setTitle(String title)
    {
        this.title = title;
    }

    /**
     * Gets the task description.
     *
     * @return The task description
     */
    public String getDescription()
    {
        return description;
    }

    /**
     * Sets the task description.
     *
     * @param description The task description
     */
    public void setDescription(String description)
    {
        this.description = description;
    }

    /**
     * Gets the due date of the task.
     *
     * @return The due date
     */
    public LocalDate getDueDate()
    {
        return dueDate;
    }

    /**
     * Sets the due date of the task.
     *
     * @param dueDate The due date
     */
    public void setDueDate(LocalDate dueDate)
    {
        this.dueDate = dueDate;
    }

    /**
     * Gets the due time of the task.
     *
     * @return The due time
     */
    public LocalTime getDueTime()
    {
        return dueTime;
    }

    /**
     * Sets the due time of the task.
     *
     * @param dueTime The due time
     */
    public void setDueTime(LocalTime dueTime)
    {
        this.dueTime = dueTime;
    }

    /**
     * Gets the priority level of the task.
     *
     * @return The priority level
     */
    public Integer getPriority()
    {
        return priority;
    }

    /**
     * Sets the priority level of the task.
     *
     * @param priority The priority level
     */
    public void setPriority(Integer priority)
    {
        this.priority = priority;
    }

    /**
     * Gets the task location.
     *
     * @return The location
     */
    public String getLocation()
    {
        return location;
    }

    /**
     * Sets the task location.
     *
     * @param location The location
     */
    public void setLocation(String location)
    {
        this.location = location;
    }

    /**
     * Checks whether the task is completed.
     *
     * @return true if completed, false otherwise
     */
    public boolean isCompleted()
    {
        return completed;
    }

    /**
     * Sets the task completion status.
     *
     * @param completed The completion status
     */
    public void setCompleted(boolean completed)
    {
        this.completed = completed;
    }

    /**
     * Gets the user who owns this task.
     *
     * @return The user who owns the task
     */
    public User getUser()
    {
        return user;
    }

    /**
     * Sets the user who owns this task.
     *
     * @param user The user who owns the task
     */
    public void setUser(User user)
    {
        this.user = user;
    }

    /**
     * Gets the task name for frontend display.
     * This allows Thymeleaf to use task.name while the backend stores the value as title.
     *
     * @return The task title
     */
    public String getName()
    {
        return title;
    }

    /**
     * Sets the task name from frontend form input.
     * This maps the frontend name field to the backend title field.
     *
     * @param name The task name entered from the frontend
     */
    public void setName(String name)
    {
        this.title = name;
    }

    /**
     * Gets the task address for frontend display.
     * This allows Thymeleaf to use task.address while the backend stores the value as location.
     *
     * @return The task location
     */
    public String getAddress()
    {
        return location;
    }

    /**
     * Sets the task address from frontend form input.
     * This maps the frontend address field to the backend location field.
     *
     * @param address The task address entered from the frontend
     */
    public void setAddress(String address)
    {
        this.location = address;
    }

    /**
     * Gets the task notes for frontend display.
     * This allows Thymeleaf to use task.notes while the backend stores the value as description.
     *
     * @return The task description
     */
    public String getNotes()
    {
        return description;
    }

    /**
     * Sets the task notes from frontend form input.
     * This maps the frontend notes field to the backend description field.
     *
     * @param notes The task notes entered from the frontend
     */
    public void setNotes(String notes)
    {
        this.description = notes;
    }

    /**
     * Gets the combined due date and due time for frontend display.
     * This allows Thymeleaf to use task.dateTime.
     *
     * @return The due date and due time combined as LocalDateTime, or null if no due date exists
     */
    public LocalDateTime getDateTime()
    {
        if (dueDate == null)
        {
            return null;
        }

        if (dueTime == null)
        {
            return dueDate.atStartOfDay();
        }

        return dueDate.atTime(dueTime);
    }

    /**
     * Sets the due date and due time from frontend datetime input.
     * This maps the frontend dateTime field to the backend dueDate and dueTime fields.
     *
     * @param dateTime The combined date and time entered from the frontend
     */
    public void setDateTime(LocalDateTime dateTime)
    {
        if (dateTime != null)
        {
            this.dueDate = dateTime.toLocalDate();
            this.dueTime = dateTime.toLocalTime();
        }
    }
}