package com.gcu.taskmanager.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Represents a user in the task management system.
 * This entity maps to the "users" table in the database.
 * A user can register, log in, and manage tasks, recurring tasks, and events.
 */
@Entity
@Table(name = "users")
public class User 
{
    /**
     * Unique identifier for the user.
     * This value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Stores the user's first name.
     */
    @Column(name = "first_name", nullable = false)
    private String firstName;

    /**
     * Stores the user's last name.
     */
    @Column(name = "last_name", nullable = false)
    private String lastName;

    /**
     * Stores the user's email address.
     */
    @Column(name = "email", nullable = false, unique = true)
    private String email;

    /**
     * Stores the user's phone number.
     */
    @Column(name = "phone_number")
    private String phoneNumber;

    /**
     * Stores the user's preferred notification method.
     * Examples: Text, Email, Both
     */
    @Column(name = "notification_method")
    private String notificationMethod;

    /**
     * Stores the user's username for logging into the application.
     */
    @Column(name = "username", nullable = false, unique = true)
    private String username;

    /**
     * Stores the user's password.
     * Note: For Milestone 2, this will be stored as plain text for simplicity.
     * In a production application, passwords should always be hashed.
     */
    @Column(name = "password", nullable = false)
    private String password;

    /**
     * Default no-argument constructor required by JPA.
     */
    public User()
    {
        super();
    }

    /**
     * Full constructor used to create a user with all required fields except ID.
     *
     * @param firstName The user's first name
     * @param lastName The user's last name
     * @param email The user's email address
     * @param phoneNumber The user's phone number
     * @param notificationMethod The user's preferred notification method
     * @param username The user's username
     * @param password The user's password
     */
    public User(String firstName, String lastName, String email, String phoneNumber, String notificationMethod,
                String username, String password)
    {
        super();
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.notificationMethod = notificationMethod;
        this.username = username;
        this.password = password;
    }

    /**
     * Gets the user ID.
     *
     * @return The user ID
     */
    public Long getId()
    {
        return id;
    }

    /**
     * Sets the user ID.
     *
     * @param id The user ID
     */
    public void setId(Long id)
    {
        this.id = id;
    }

    /**
     * Gets the user's first name.
     *
     * @return The first name
     */
    public String getFirstName()
    {
        return firstName;
    }

    /**
     * Sets the user's first name.
     *
     * @param firstName The first name
     */
    public void setFirstName(String firstName)
    {
        this.firstName = firstName;
    }

    /**
     * Gets the user's last name.
     *
     * @return The last name
     */
    public String getLastName()
    {
        return lastName;
    }

    /**
     * Sets the user's last name.
     *
     * @param lastName The last name
     */
    public void setLastName(String lastName)
    {
        this.lastName = lastName;
    }

    /**
     * Gets the user's email address.
     *
     * @return The email address
     */
    public String getEmail()
    {
        return email;
    }

    /**
     * Sets the user's email address.
     *
     * @param email The email address
     */
    public void setEmail(String email)
    {
        this.email = email;
    }

    /**
     * Gets the user's phone number.
     *
     * @return The phone number
     */
    public String getPhoneNumber()
    {
        return phoneNumber;
    }

    /**
     * Sets the user's phone number.
     *
     * @param phoneNumber The phone number
     */
    public void setPhoneNumber(String phoneNumber)
    {
        this.phoneNumber = phoneNumber;
    }

    /**
     * Gets the user's preferred notification method.
     *
     * @return The notification method
     */
    public String getNotificationMethod()
    {
        return notificationMethod;
    }

    /**
     * Sets the user's preferred notification method.
     *
     * @param notificationMethod The notification method
     */
    public void setNotificationMethod(String notificationMethod)
    {
        this.notificationMethod = notificationMethod;
    }

    /**
     * Gets the user's username.
     *
     * @return The username
     */
    public String getUsername()
    {
        return username;
    }

    /**
     * Sets the user's username.
     *
     * @param username The username
     */
    public void setUsername(String username)
    {
        this.username = username;
    }

    /**
     * Gets the user's password.
     *
     * @return The password
     */
    public String getPassword()
    {
        return password;
    }

    /**
     * Sets the user's password.
     *
     * @param password The password
     */
    public void setPassword(String password)
    {
        this.password = password;
    }
}