spring.application.name=TaskManager

# AWS RDS MySQL Database
spring.datasource.url=jdbc:mysql://taskmanager-db.c8jyuyioul7w.us-east-1.rds.amazonaws.com:3306/taskmanagerdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=Raichi0824

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=5000